az-configuration: ((az-configuration))

iaas-configurations:
- additional_cloud_properties: {}
  bosh_disk_path: ((iaas-configurations.bosh_disk_path))
  bosh_template_folder: ((iaas-configurations.bosh_template_folder))
  bosh_vm_folder: ((iaas-configurations.bosh_vm_folder))
  datacenter: ((iaas-configurations.datacenter))
  disk_type: ((iaas-configurations.disk_type))
  ephemeral_datastores_string: ((iaas-configurations.ephemeral_datastores_string))
  name: ((iaas-configurations.name))
  nsx_address: ((iaas-configurations.nsx_address))
  nsx_ca_certificate: ((iaas-configurations.nsx_ca_certificate))
  nsx_mode: ((iaas-configurations.nsx_mode))
  nsx_networking_enabled: ((iaas-configurations.nsx_networking_enabled))
  nsx_username: ((iaas-configurations.nsx_username))
  nsx_password: ((iaas-configurations.nsx_password))
  persistent_datastores_string: ((iaas-configurations.persistent_datastores_string))
  ssl_verification_enabled: ((iaas-configurations.ssl_verification_enabled))
  vcenter_host: ((iaas-configurations.vcenter_host))
  vcenter_username: ((iaas-configurations.vcenter_username))
  vcenter_password: ((iaas-configurations.vcenter_password))

network-assignment:
  network:
    name: ((network-assignment.network))
  other_availability_zones: []
  singleton_availability_zone:
    name: ((network-assignment.singleton_availability_zone))

networks-configuration:
  icmp_checks_enabled: ((networks-configuration.icmp_checks_enabled))
  networks: ((networks-configuration.networks))

properties-configuration:
  director_configuration:
    blobstore_type: local
    bosh_recreate_on_next_deploy: false
    bosh_recreate_persistent_disks_on_next_deploy: false
    database_type: internal
    director_worker_count: 5
    encryption:
      keys: []
      providers: []
    hm_emailer_options:
      enabled: false
    hm_pager_duty_options:
      enabled: false
    identification_tags: {}
    job_configuration_on_tmpfs: false
    keep_unreachable_vms: false
    local_blobstore_options:
      tls_enabled: true
    ntp_servers_string: ((properties-configuration.director_configuration.ntp_servers_string))
    post_deploy_enabled: ((properties-configuration.director_configuration.post_deploy_enabled))
    resurrector_enabled: ((properties-configuration.director_configuration.resurrector_enabled))
    retry_bosh_deploys: ((properties-configuration.director_configuration.retry_bosh_deploys))
    skip_director_drain: false
  dns_configuration:
    excluded_recursors: []
    handlers: []
  security_configuration:
    generate_vm_passwords: ((properties-configuration_security_configuration_generate_vm_passwords))
    opsmanager_root_ca_trusted_certs: ((security_configuration.opsmanager_root_ca_trusted_certs))
    trusted_certificates: ((security_configuration.trusted_certificates))
  syslog_configuration:
    enabled: false
resource-configuration:
  compilation:
    instances: automatic
    instance_type:
      id: automatic
  director:
    instances: automatic
    persistent_disk:
      size_mb: ((director.persistent_disk))
    instance_type:
      id: ((director.instance_type))

vmextensions-configuration: []
vmtypes-configuration: {}

